apiVersion: v1
kind: Service
metadata:
  name: recipes-postgres-service
  namespace: team-tikchalal
spec:
  selector:
    app: recipes-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
