apiVersion: v1
kind: Service
metadata:
  name: recipes-server-service
  namespace: team-tikchalal
spec:
  selector:
    app: recipes-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
