services:
  server:
    image: recipes:v1.0.0
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    env_file:
      - .env
    restart: "always"

  db:
    image: postgres:15
    ports:
      - "${DB_PORT}:${DB_PORT}"

    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
