FROM node:18 AS builder
WORKDIR /app
COPY backend/package*.json ./backend/
COPY shared/package*.json ./shared/
WORKDIR /app/backend
RUN npm install
COPY backend/ ./
COPY shared/ ../shared/
RUN npm run build

FROM node:18-alpine
WORKDIR /app
ENV IS_DOCKER=true
COPY --from=builder /app/backend/package*.json ./
RUN npm install --production
COPY --from=builder /app/backend/dist ./dist
COPY --from=builder /app/shared ./shared
EXPOSE 8080
CMD ["npm", "run", "start"]