apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: recipes-pgdata-pvc
  namespace: team-tikchalal
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3
  resources:
    requests:
      storage: 20Gi
