apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - recipes-secrets.yaml
  - server-service.yaml
  - server-configmap.yaml
  - server-deployment.yaml
  - ingress.yaml
  - client-deployment.yaml
  - client-service.yaml

namespace: team-tikchalal

labels:
  - pairs:
      env: dev
      project: recipes
