apiVersion: v1
kind: Secret
metadata:
  name: recipes-secrets
  namespace: team-tikchalal
type: Opaque
data:
  DB_PORT: NTQzMg==
  DB_HOST: bmlmZ2FpbS5jam80eTJqenp5N2MuaWwtY2VudHJhbC0xLnJkcy5hbWF6b25hd3MuY29t
  DB_USERNAME: bmlmZ2FpbUFkbWlu
  DB_NAME: cG9zdGdyZXM=
  DB_SCHEMA: cmVjaXBlcw==
  VITE_PORT: NTE3Mw==
